#ifndef SERIALHANDLER_GLOBAL_H
#define SERIALHANDLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERIALHANDLER_LIBRARY)
#  define SERIALHANDLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERIALHANDLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SERIALHANDLER_GLOBAL_H
