#ifndef ZIGBEEDEFS_H
#define ZIGBEEDEFS_H

#define SERIAL_TX_MODE          0x01
#define REQUEST_SENSOR_MODE     0x08

#define START_ZIGBEE_PACKAGE    0x7E

#define MAX_ZIGBEE_SIZE 2000

#define MOBILE_API_NODE_TYPE            SERIAL_TX_MODE
#define STATIC_TRANSPARENT_NODE_TYPE    REQUEST_SENSOR_MODE

#endif // ZIGBEEDEFS_H
